version: '3'

volumes:
  pg_data_kit:
  static:
  media_kit:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kit:/var/lib/postgresql/data
  backend:
    image: ingarbi/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media_kit:/media
  frontend:
    env_file: .env
    image: ingarbi/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: ingarbi/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media_kit:/media
